version: '3'

services:
  crawl4ai:
    image: unclecode/crawl4ai:basic
    container_name: crawl4ai
    restart: unless-stopped
    ports:
      - "11235:11235"
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - app-network

networks:
  app-network:
    external: true 