version: '3'

services:
  crawl4ai:
    image: unclecode/crawl4ai:basic
    container_name: crawl4ai
    restart: unless-stopped
    ports:
      - "11235:11235"
    environment:
      - CHROME_PATH=/usr/bin/chromium-browser
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - MAX_CONCURRENT_TASKS=5
    volumes:
      - /dev/shm:/dev/shm
      - crawl4ai_data:/app/data
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      - app-network

volumes:
  crawl4ai_data:

networks:
  app-network:
    external: true 