version: '3'

services:
  zep:
    image: ghcr.io/getzep/zep-cloud:latest
    container_name: zep
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Store configuration
      - ZEP_STORE_TYPE=postgres
      - ZEP_MEMORY_STORE_POSTGRES_DSN=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      # NLP configuration
      - ZEP_NLP_SERVER_TYPE=local
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: zep-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    external: true 